# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../GUI Files/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1507, 849)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(45, 45, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color:#7289DA;")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.Top_Bar)
        self.label_3.setStyleSheet("color: #FFFFFF;\n"
                                   "font-weight: bold")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.to_taskbar_button = QtWidgets.QPushButton(self.Top_Bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.to_taskbar_button.sizePolicy().hasHeightForWidth())
        self.to_taskbar_button.setSizePolicy(sizePolicy)
        self.to_taskbar_button.setMinimumSize(QtCore.QSize(35, 35))
        self.to_taskbar_button.setMaximumSize(QtCore.QSize(35, 35))
        self.to_taskbar_button.setStyleSheet("QPushButton {\n"
                                             "color: rgb(255, 255, 255);\n"
                                             "border: 0px solid;\n"
                                             "background-color:#232323 ;\n"
                                             "padding:0.5em;\n"
                                             "font-weight:900;\n"
                                             "font-size:12px;\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    background-color:#5b6dae ;\n"
                                             "\n"
                                             "}")
        self.to_taskbar_button.setObjectName("to_taskbar_button")
        self.horizontalLayout.addWidget(self.to_taskbar_button)
        self.quit_button = QtWidgets.QPushButton(self.Top_Bar)
        self.quit_button.setMinimumSize(QtCore.QSize(35, 35))
        self.quit_button.setMaximumSize(QtCore.QSize(35, 35))
        self.quit_button.setStyleSheet("QPushButton {\n"
                                       "color: rgb(255, 255, 255);\n"
                                       "border: 0px solid;\n"
                                       "background-color:  #232323;\n"
                                       "padding:0.5em;\n"
                                       "font-weight:bold;\n"
                                       "font-size:12px;\n"
                                       "\n"
                                       "}\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: #c42b2b;\n"
                                       "}")
        self.quit_button.setObjectName("quit_button")
        self.horizontalLayout.addWidget(self.quit_button)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_left_menu)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setMaximumSize(QtCore.QSize(60, 16777215))
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.VLine)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_top_menus.setLineWidth(1)
        self.frame_top_menus.setMidLineWidth(0)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(60, 50))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid;\n"
                                      "    font-weight:700;\n"
                                      "    font-size:12px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #7289DA;\n"
                                      "}")
        self.btn_page_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Resources/icons/32px/video-cam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_page_1.setIcon(icon)
        self.btn_page_1.setIconSize(QtCore.QSize(48, 48))
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_4.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(60, 50))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid;\n"
                                      "font-weight:700;\n"
                                      "    font-size:12px;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #7289DA;\n"
                                      "}")
        self.btn_page_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Resources/icons/32px/stat_light_gray.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btn_page_2.setIcon(icon1)
        self.btn_page_2.setIconSize(QtCore.QSize(32, 32))
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_4.addWidget(self.btn_page_2)
        self.btn_page_4 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_4.setEnabled(True)
        self.btn_page_4.setMinimumSize(QtCore.QSize(60, 50))
        self.btn_page_4.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(255, 255, 255);\n"
                                      "    background-color: rgb(35, 35, 35);\n"
                                      "    border: 0px solid;\n"
                                      "    font-weight:700;\n"
                                      "    font-size:12px;\n"
                                      "     border-radius: 25px;\n"
                                      "    border-style: outset;\n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: #1f1f1f;\n"
                                      "}")
        self.btn_page_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Resources/icons/32px/user_alternative.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.btn_page_4.setIcon(icon2)
        self.btn_page_4.setIconSize(QtCore.QSize(32, 32))
        self.btn_page_4.setObjectName("btn_page_4")
        self.verticalLayout_4.addWidget(self.btn_page_4)
        self.horizontalLayout_3.addWidget(self.frame_top_menus)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setMaximumSize(QtCore.QSize(16777207, 16777215))
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(5, -1, 5, 10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.image_frame = QtWidgets.QLabel(self.page_1)
        self.image_frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.image_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_frame.setLineWidth(3)
        self.image_frame.setText("")
        self.image_frame.setPixmap(QtGui.QPixmap(":/placeholders/Resources/placeholder2.png"))
        self.image_frame.setScaledContents(True)
        self.image_frame.setObjectName("image_frame")
        self.gridLayout_5.addWidget(self.image_frame, 0, 0, 1, 4)
        self.start_stop_button = QtWidgets.QPushButton(self.page_1)
        self.start_stop_button.setMinimumSize(QtCore.QSize(0, 50))
        self.start_stop_button.setMaximumSize(QtCore.QSize(480, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 137, 218))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.start_stop_button.setPalette(palette)
        self.start_stop_button.setStyleSheet("QPushButton {\n"
                                             "color: rgb(255, 255, 255);\n"
                                             "border: 0px solid;\n"
                                             "background-color:  #7289DA;\n"
                                             "padding:0.5em;\n"
                                             "font-weight:bold;\n"
                                             "font-size:12px;\n"
                                             "}\n"
                                             "QPushButton:hover {\n"
                                             "    background-color: #667bc4;\n"
                                             "}")
        self.start_stop_button.setObjectName("start_stop_button")
        self.gridLayout_5.addWidget(self.start_stop_button, 2, 0, 1, 1)
        self.media_source_combobox = QtWidgets.QComboBox(self.page_1)
        self.media_source_combobox.setMinimumSize(QtCore.QSize(0, 25))
        self.media_source_combobox.setMaximumSize(QtCore.QSize(960, 16777215))
        self.media_source_combobox.setAutoFillBackground(False)
        self.media_source_combobox.setStyleSheet("QComboBox{\n"
                                                 "background-color: #2C2F33;\n"
                                                 "font-size:12px;\n"
                                                 "color:#FFFFFF;\n"
                                                 "font-weight:700;\n"
                                                 "\n"
                                                 "}\n"
                                                 "QComboBox:hover\n"
                                                 "{\n"
                                                 "    border: 1px solid white;\n"
                                                 "    background-color:#1a1c1e;\n"
                                                 "}\n"
                                                 "QListView\n"
                                                 "{\n"
                                                 "background-color: #2C2F33;\n"
                                                 "font-size:12px;\n"
                                                 "color:#FFFFFF;\n"
                                                 "font-weight:700;\n"
                                                 "}\n"
                                                 "")
        self.media_source_combobox.setCurrentText("")
        self.media_source_combobox.setObjectName("media_source_combobox")
        self.gridLayout_5.addWidget(self.media_source_combobox, 1, 0, 1, 1)
        self.info_title_box = QtWidgets.QLabel(self.page_1)
        self.info_title_box.setMaximumSize(QtCore.QSize(100, 16777215))
        self.info_title_box.setStyleSheet("color: #FFFFFF;\n"
                                          "font-weight: bold;\n"
                                          "font-size:12px;\n"
                                          "margin-left:1em;\n"
                                          "")
        self.info_title_box.setObjectName("info_title_box")
        self.gridLayout_5.addWidget(self.info_title_box, 1, 1, 2, 1)
        self.out_info_box = QtWidgets.QLabel(self.page_1)
        self.out_info_box.setStyleSheet("color: #FFFFFF;\n"
                                        "font-size:12px;")
        self.out_info_box.setText("")
        self.out_info_box.setObjectName("out_info_box")
        self.gridLayout_5.addWidget(self.out_info_box, 1, 2, 2, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 1, 1)
        self.reload_table_button = QtWidgets.QPushButton(self.page_2)
        self.reload_table_button.setMinimumSize(QtCore.QSize(400, 60))
        self.reload_table_button.setMaximumSize(QtCore.QSize(500, 16777215))
        self.reload_table_button.setStyleSheet("QPushButton {\n"
                                               "color: rgb(255, 255, 255);\n"
                                               "border: 0px solid;\n"
                                               "background-color:  #7289DA;\n"
                                               "padding:0.5em;\n"
                                               "font-weight:700;\n"
                                               "font-size:14px;\n"
                                               "}\n"
                                               "QPushButton:hover {\n"
                                               "    background-color: #667bc4;\n"
                                               "}")
        self.reload_table_button.setObjectName("reload_table_button")
        self.gridLayout_3.addWidget(self.reload_table_button, 3, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 3, 2, 1, 1)
        self.report_table = QtWidgets.QTableWidget(self.page_2)
        self.report_table.setMinimumSize(QtCore.QSize(800, 0))
        self.report_table.setStyleSheet("QTableView {\n"
                                        "    selection-background-color: #232323;\n"
                                        "    background-color: #2d2d2d;\n"
                                        "    alternate-background-color: #2b2b2b;\n"
                                        "    color: #FFFFFF;\n"
                                        "    font-size: 14px;\n"
                                        "\n"
                                        "}\n"
                                        "\n"
                                        "QTableView QTableCornerButton::section {\n"
                                        "    background: #434343;\n"
                                        "    border: 0px solid;\n"
                                        "}\n"
                                        "QTableWidget {\n"
                                        "    gridline-color: #1e1e1e;\n"
                                        "}\n"
                                        "\n"
                                        "QHeaderView::section {\n"
                                        "    padding-top:4px;\n"
                                        "       padding-bottom:4px;\n"
                                        "    padding-left:-0.5em;\n"
                                        "    background-color:#2a2a2a;\n"
                                        "    color:#FFFFFF;\n"
                                        "    border: 0px solid #fffff8;\n"
                                        "    font-weight: 800;\n"
                                        "    font-size:16px;\n"
                                        "}")
        self.report_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.report_table.setFrameShadow(QtWidgets.QFrame.Raised)
        self.report_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.report_table.setAlternatingRowColors(True)
        self.report_table.setShowGrid(True)
        self.report_table.setGridStyle(QtCore.Qt.NoPen)
        self.report_table.setRowCount(10)
        self.report_table.setColumnCount(4)
        self.report_table.setObjectName("report_table")
        item = QtWidgets.QTableWidgetItem()
        self.report_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.report_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.report_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.report_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.report_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.report_table.setItem(1, 1, item)
        self.report_table.horizontalHeader().setDefaultSectionSize(200)
        self.report_table.horizontalHeader().setMinimumSectionSize(50)
        self.report_table.verticalHeader().setVisible(False)
        self.report_table.verticalHeader().setDefaultSectionSize(50)
        self.report_table.verticalHeader().setMinimumSectionSize(28)
        self.gridLayout_3.addWidget(self.report_table, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.report_info_box = QtWidgets.QLabel(self.page_2)
        self.report_info_box.setStyleSheet("color: #ff5048;\n"
                                           "font-weight: 700;\n"
                                           "font-size: 14px;\n"
                                           "margin:2em;\n"
                                           "")
        self.report_info_box.setObjectName("report_info_box")
        self.gridLayout_3.addWidget(self.report_info_box, 1, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.stackedWidget.addWidget(self.page_2)
        self.sign_in_page = QtWidgets.QWidget()
        self.sign_in_page.setObjectName("sign_in_page")
        self.gridLayout = QtWidgets.QGridLayout(self.sign_in_page)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.info_box = QtWidgets.QLabel(self.sign_in_page)
        self.info_box.setMaximumSize(QtCore.QSize(16777215, 100))
        self.info_box.setStyleSheet("color: #ff5048;\n"
                                    "font-weight: 700;\n"
                                    "")
        self.info_box.setText("")
        self.info_box.setObjectName("info_box")
        self.gridLayout_4.addWidget(self.info_box, 3, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.email_lbl_2 = QtWidgets.QLabel(self.sign_in_page)
        self.email_lbl_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "border: 0px solid;\n"
                                       "font-weight:700;\n"
                                       "font-size:12px;\n"
                                       "margin-right:1em;\n"
                                       "margin-bottom:2em;")
        self.email_lbl_2.setObjectName("email_lbl_2")
        self.gridLayout_4.addWidget(self.email_lbl_2, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.sign_in_button = QtWidgets.QPushButton(self.sign_in_page)
        self.sign_in_button.setMinimumSize(QtCore.QSize(150, 35))
        self.sign_in_button.setStyleSheet("QPushButton {\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "border: 0px solid;\n"
                                          "background-color:  #7289DA;\n"
                                          "padding:0.1em;\n"
                                          "font-weight:bold;\n"
                                          "font-size:12px;\n"
                                          "}\n"
                                          "QPushButton:hover {\n"
                                          "    background-color: #667bc4;\n"
                                          "}")
        self.sign_in_button.setObjectName("sign_in_button")
        self.gridLayout_4.addWidget(self.sign_in_button, 2, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.password_lbl_2 = QtWidgets.QLabel(self.sign_in_page)
        self.password_lbl_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                          "border: 0px solid;\n"
                                          "font-weight:700;\n"
                                          "font-size:12px;\n"
                                          "margin-right:1em;\n"
                                          "margin-bottom:3em;\n"
                                          "")
        self.password_lbl_2.setObjectName("password_lbl_2")
        self.gridLayout_4.addWidget(self.password_lbl_2, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.email = QtWidgets.QLineEdit(self.sign_in_page)
        self.email.setMinimumSize(QtCore.QSize(400, 0))
        self.email.setMaximumSize(QtCore.QSize(450, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.email.setPalette(palette)
        self.email.setStyleSheet("background-color: rgb(35,35,35);\n"
                                 "color: #FFFFFF;\n"
                                 "border: 0px solid;\n"
                                 "padding:0.5em;\n"
                                 "margin-bottom:2em;\n"
                                 "\n"
                                 "")
        self.email.setMaxLength(64)
        self.email.setClearButtonEnabled(False)
        self.email.setObjectName("email")
        self.gridLayout_4.addWidget(self.email, 0, 1, 1, 1)
        self.password = QtWidgets.QLineEdit(self.sign_in_page)
        self.password.setMinimumSize(QtCore.QSize(400, 0))
        self.password.setMaximumSize(QtCore.QSize(450, 16777215))
        self.password.setStyleSheet("background-color: rgb(35,35,35);\n"
                                    "color: #FFFFFF;\n"
                                    "border: 0px solid;\n"
                                    "padding:0.5em;\n"
                                    "margin-bottom:3em;\n"
                                    "")
        self.password.setMaxLength(39)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(False)
        self.password.setObjectName("password")
        self.gridLayout_4.addWidget(self.password, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.sign_in_page)
        self.profile_page = QtWidgets.QWidget()
        self.profile_page.setObjectName("profile_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.profile_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.profile_page)
        self.label_5.setMaximumSize(QtCore.QSize(800, 50))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "border: 0px solid;\n"
                                   "font-weight:800;\n"
                                   "font-size:13px;\n"
                                   "margin-right:1em;")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label = QtWidgets.QLabel(self.profile_page)
        self.label.setMaximumSize(QtCore.QSize(100, 50))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                 "border: 0px solid;\n"
                                 "font-weight:800;\n"
                                 "font-size:13px;\n"
                                 "margin-right:1em;")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.profile_page)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "border: 0px solid;\n"
                                   "font-weight:800;\n"
                                   "font-size:14px;\n"
                                   "margin-bottom: 1.5em;\n"
                                   "")
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.profile_info_box = QtWidgets.QLabel(self.profile_page)
        self.profile_info_box.setMaximumSize(QtCore.QSize(16777215, 200))
        self.profile_info_box.setStyleSheet("color: #2dbd2d;\n"
                                            "font-weight: 700;\n"
                                            "margin-top:3em;\n"
                                            "font-size:13px;\n"
                                            "")
        self.profile_info_box.setText("")
        self.profile_info_box.setObjectName("profile_info_box")
        self.gridLayout_2.addWidget(self.profile_info_box, 7, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.profile_page)
        self.label_2.setMaximumSize(QtCore.QSize(800, 50))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "border: 0px solid;\n"
                                   "font-weight:800;\n"
                                   "font-size:13px;\n"
                                   "margin-right:1em;")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.current_name_surname = QtWidgets.QLabel(self.profile_page)
        self.current_name_surname.setMaximumSize(QtCore.QSize(16777215, 50))
        self.current_name_surname.setStyleSheet("color: rgb(255, 255, 255);\n"
                                                "border: 0px solid;\n"
                                                "font-weight:400;\n"
                                                "font-size:12px;\n"
                                                "")
        self.current_name_surname.setObjectName("current_name_surname")
        self.gridLayout_2.addWidget(self.current_name_surname, 3, 1, 1, 1)
        self.sign_out_button = QtWidgets.QPushButton(self.profile_page)
        self.sign_out_button.setMinimumSize(QtCore.QSize(100, 30))
        self.sign_out_button.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.sign_out_button.setStyleSheet("QPushButton {\n"
                                           "color: rgb(255, 255, 255);\n"
                                           "border: 0px solid;\n"
                                           "background-color:  #FF392E;\n"
                                           "margin-top:2.5em;\n"
                                           "padding:0.5em;\n"
                                           "padding-left:5em;\n"
                                           "padding-right:5em;\n"
                                           "font-weight:bold;\n"
                                           "font-size:12px;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: #FF2115;\n"
                                           "}")
        self.sign_out_button.setObjectName("sign_out_button")
        self.gridLayout_2.addWidget(self.sign_out_button, 6, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.current_email = QtWidgets.QLabel(self.profile_page)
        self.current_email.setMaximumSize(QtCore.QSize(16777215, 50))
        self.current_email.setStyleSheet("color: rgb(255, 255, 255);\n"
                                         "border: 0px solid;\n"
                                         "font-weight:400;\n"
                                         "font-size:12px;")
        self.current_email.setObjectName("current_email")
        self.gridLayout_2.addWidget(self.current_email, 4, 1, 1, 1)
        self.pc_id_combo = QtWidgets.QComboBox(self.profile_page)
        self.pc_id_combo.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pc_id_combo.setStyleSheet("QComboBox{\n"
                                       "background-color: #2C2F33;\n"
                                       "font-size:12px;\n"
                                       "color:#FFFFFF;\n"
                                       "font-weight:500;\n"
                                       "\n"
                                       "}\n"
                                       "QComboBox:hover\n"
                                       "{\n"
                                       "    border: 1px solid white;\n"
                                       "    background-color:#1a1c1e;\n"
                                       "}\n"
                                       "QListView\n"
                                       "{\n"
                                       "background-color: #2C2F33;\n"
                                       "font-size:12px;\n"
                                       "color:#FFFFFF;\n"
                                       "font-weight:400;\n"
                                       "}\n"
                                       "")
        self.pc_id_combo.setObjectName("pc_id_combo")
        self.pc_id_combo.addItem("")
        self.gridLayout_2.addWidget(self.pc_id_combo, 5, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.stackedWidget.addWidget(self.profile_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "    Object Detective Alpha version 0.95"))
        self.to_taskbar_button.setText(_translate("MainWindow", "_"))
        self.quit_button.setText(_translate("MainWindow", "X"))
        self.btn_page_1.setToolTip(_translate("MainWindow", "Ana Ekran"))
        self.btn_page_2.setToolTip(_translate("MainWindow", "Raporlar"))
        self.btn_page_4.setToolTip(_translate("MainWindow", "Hesabınız"))
        self.start_stop_button.setText(_translate("MainWindow", "Başlat"))
        self.info_title_box.setText(_translate("MainWindow", " Sol Toplam\n"
                                                             "Sağ Toplam\n"
                                                             "       Durum"))
        self.reload_table_button.setText(_translate("MainWindow", "Yenile"))
        self.report_table.setSortingEnabled(False)
        item = self.report_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Tarih"))
        item = self.report_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Geçen  Süre"))
        item = self.report_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Dışarı Çıkan"))
        item = self.report_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "İçeri Giren"))
        __sortingEnabled = self.report_table.isSortingEnabled()
        self.report_table.setSortingEnabled(False)
        self.report_table.setSortingEnabled(__sortingEnabled)
        self.report_info_box.setText(_translate("MainWindow", "Test"))
        self.email_lbl_2.setText(_translate("MainWindow", "E-posta:"))
        self.sign_in_button.setText(_translate("MainWindow", "Giriş Yap"))
        self.password_lbl_2.setText(_translate("MainWindow", "Parola:"))
        self.email.setPlaceholderText(_translate("MainWindow", "Örn. provactus@domain.com"))
        self.password.setPlaceholderText(_translate("MainWindow", "******"))
        self.label_5.setText(_translate("MainWindow", "PC ID:"))
        self.label.setText(_translate("MainWindow", "Ad Soyad: "))
        self.label_4.setText(_translate("MainWindow", "Kullanıcı Bilgileri"))
        self.label_2.setText(_translate("MainWindow", " E-posta: "))
        self.current_name_surname.setText(_translate("MainWindow", "Testson"))
        self.sign_out_button.setText(_translate("MainWindow", "Çıkış Yap"))
        self.current_email.setText(_translate("MainWindow", "test@domain.com"))
        self.pc_id_combo.setItemText(0, _translate("MainWindow", "1"))